### Problem 1

In [6]:
using PyPlot
using Random
Random.seed!(1234)
function generate_n_randomnum(n)
    num = Float64[]
    while length(num) < n
        x = 10*rand()
        if (x<=2)||(x>=7)
            push!(num,x)
        end
    end
    return num
end
g = generate_n_randomnum(10)
g

10-element Vector{Float64}:
 8.942454282009884
 9.53124627284842
 7.955469475347194
 7.484150218874741
 7.279350012266056
 0.07448006132865004
 1.9937661409915552
 9.567409540049077
 9.96665291437684
 7.491940599574348

### Problem 2

In [25]:
function simulate_prob_complex(n)
    comp = 0
    for i in 1:n
        a = 4rand()-2
        b = 4rand()-2
        c = 4rand()-2
        if (b^2-4a*c) < 0
            comp += 1
        end
    end
    return comp/n
end
simulate_prob_complex(100)
function simulate_normprob_complex(n)
    comp = 0
    x = 0
    y = 0.4
    for i in 1:n
        a = y*randn() + x
        b = y*randn() + x
        c = y*randn() + x
        if (b^2-4a*c) < 0
            comp += 1
        end
    end
    return comp/n
end
simulate_normprob_complex(1000)

0.379

### Problem 3

In [61]:
function simulate_unit_circle(n)
    m = 0
    for i in 1:n
        angle1 = 2π*rand()  # Random angle in radians
        x1 = cos(angle1)
        y1 = sin(angle1)

        angle2 = 2π*rand()  # Random angle in radians
        x2 = cos(angle2)
        y2 = sin(angle2)
    
        if sqrt((x2-x1)^2+(y2-y1)^2) > 1
            m += 1
        end
    end
    return m/n
end
simulate_unit_circle(10000)

0.6692

### Problem 4

In [70]:
function f(x)
    return 1/sqrt(2*(pi))*exp(-(x^2)/2)
end
function ProbG(L,R)
    n = 100000000
    m = 0
    for i in 1:n
        x = (L-R)*rand()+L
        y = rand()
        if y < f(x)
            m += 1
        end
    end
    return m/n
end
ProbG(0,2)

0.23867109

### Problem 5

In [105]:
function random_walk(n)
    x = [0]
    y = [0]
    while abs(x[end]) < n && abs(y[end]) < n
        if rand() < 0.5
            if rand() < 0.5  # Up
                push!(x, x[end])
                push!(y, y[end] + 1)
            else             # Down
                push!(x, x[end])
                push!(y, y[end] - 1)
            end
        else
            if rand() < 0.5  # Right
                push!(x, x[end] + 1)
                push!(y, y[end])
            else             # Left    
                push!(x, x[end] - 1)
                push!(y, y[end])
            end
        end
    end
    x,y
end    

function exit_middle(n,i)
    m = 0
    for i in 1:i
        x,y = random_walk(n)
        if ((x[end] < 10) & (x[end] > -10)) | ((y[end]< 10)&(y[end] > -10))
            m += 1
        end
    end
    return m/i
end
n = 20
x = 10000
exit_middle(n,x)

0.7014

### Problem 6

In [143]:
function card_rank(card)
    (card - 1) % 13 + 1
end
function card_suit(card)
    (card - 1) ÷ 13 + 1
end
function card_deck()
    cards = 1:52      # All cards
    return [card_rank.(cards) card_suit.(cards)]
end

function draw_card(n)
    cards = randperm(52)
    hand = cards[1:n]
    [card_rank.(hand) card_suit.(hand)]
end

function two_pairs(c)
    num = 0
    for i in 1:size(c,1)
        for j in i+1:size(c,1)
            if c[i,1] == c[j,1]
                num += 1
            end
        end
    end
    if num == 2
        return true
    else
        return false
    end
end

function two_pair_prob(n)
    m = 0
    for i in 1:n
        c = draw_card(5)
        if two_pairs(c)
            m += 1
        end
    end
    return m/n
end
two_pair_prob(1000000)

0.047601

### Problem 7(a)

In [145]:
A = reshape((-22:22) .% 11, 9, 5) # For testing

9×5 Matrix{Int64}:
   0   -2  -4   5   3
 -10   -1  -3   6   4
  -9    0  -2   7   5
  -8  -10  -1   8   6
  -7   -9   0   9   7
  -6   -8   1  10   8
  -5   -7   2   0   9
  -4   -6   3   1  10
  -3   -5   4   2   0

In [150]:
length(A[findall(x -> (x^2 < 10),A)])

17

### Problem 7(b)

In [172]:
A[:,findall(x -> x>0,A[1,:])]

9×2 Matrix{Int64}:
  5   3
  6   4
  7   5
  8   6
  9   7
 10   8
  0   9
  1  10
  2   0

### Problem 7(c)

In [173]:
for i in 1:size(A,1)
    for j in 1:size(A,2)
        if A[i,j]%2 == 0
            A[i,j] *= 3
        end
    end
end
A

9×5 Matrix{Int64}:
   0   -6  -12   5   3
 -30   -1   -3  18  12
  -9    0   -6   7   5
 -24  -30   -1  24  18
  -7   -9    0   9   7
 -18  -24    1  30  24
  -5   -7    6   0   9
 -12  -18    3   1  30
  -3   -5   12   6   0